spring:
  datasource:
    username: StationChnqoo
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/DiaryUat?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource

    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 6000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开 PSCache，并且指定每个连接上 PSCache 的大小
    pool-prepared-statements: true
    # 配置监控统计拦截的 Filters，去掉后监控界面 SQL 无法统计，Wall 用于防火墙
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat, wall
    use-global-data-source-stat: true
    # 通过 ConnectProperties 属性来打开 mergeSQL功能；慢 SQL 记录
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  # The field file exceeds its maximum permitted size of 1048576 bytes.
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB

server:
  port: 21983

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config: classpath:log4j.properties

my-config:
  upload-real-path: /root/net.cctv3.iCloud/public
  upload-cdn-path: https://cloud.cctv3.net
  environment: Alpha